services:
  db:
    image: postgres:14
    container_name: budget-db
    environment:
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: budget-api
    depends_on:
      - db
    env_file:
      - ./secrets/.env
    environment:
      #FLASK_APP: app.budget_app
      FLASK_APP: "app:create_app"
      #FLASK_APP: budget_app
      FLASK_ENV: development
    working_dir: /app #remove this for deployment
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app #remove this for deploy
      - ./migrations:/app/migrations  # persist migrations
      - ./entrypoint.sh:/entrypoint.sh # ensure entrypoint is visible
    command: ./entrypoint.sh
    restart: always

volumes:
  postgres_data:

